name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      
    - name: Unzip Source File
      run: |
        unzip -o plugin.zip
        # যদি জিপের ভেতর অন্য কোনো ফোল্ডারের আড়ালে src থাকে, তা মেইন স্ক্রিনে নিয়ে আসবে
        find . -type d -name "src" -exec mv {}/. ./src \; 2>/dev/null || true
      
    - name: Build with Gradle
      run: gradle jar
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: InvisibleAdPlugin-1.26
        path: build/libs/*.jar
